import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import useSWR, { useSWRConfig } from 'swr'
import styles from '../styles/Home.module.css'

const fetcher = (...args) => fetch(...args).then(res => res.json())

const Home: NextPage = () => {
  const { mutate } = useSWRConfig()
  const { data, error } = useSWR('http://localhost:3000/task', fetcher)
  const [title, setTitle] = useState<string>('');
  const [content, setContent] = useState<string>('');

  const handleClick = async () => {
    const obj = {
      title,
      content
    };
    const method = "POST";
    const body = JSON.stringify(obj);
    const headers = {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    };

    mutate('http://localhost:3000/task', [...data, obj], false)

    await fetch("http://localhost:3000/task", {method, headers, body});
    mutate('http://localhost:3000/task')
  }

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/mvp.css"></link>
      </Head>


      <main className={styles.main}>
        <input type="text" onChange={(e) => setTitle(e.target.value)} placeholder='title'/>
        <textarea onChange={(e) => setContent(e.target.value)} placeholder='content'/>
        <button onClick={handleClick}>Add</button>
        <ul>
          {data.map((d, index) => {
            return (
              <li key={index}>
                {d.title}: {d.content}
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
