version: '3.9'

services:
  postgres:
    container_name: local-postgres
    build: docker/postgres
    ports:
      - '5432:5432'
    hostname: dbserver
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  # app:
  #   container_name: go
  #   build:
  #     context: .
  #     dockerfile: docker/go/Dockerfile
  #   links:
  #     - postgres
  #   tty: true
  #   ports:
  #     - 8080:8080

volumes:
  pgdata:
    name: nestjs-prisma-local-db
